name: Pull Request
on: [pull_request]
env:
  # NOTE: APP_SERVER is used as output in few steps so it cannot be
  # secret (Github would fail to output). As the server is also
  # used in public github comments it's fine to have it here.
  APP_SERVER: https://onlineinquirytool.org
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          cache: 'pnpm' # cache example form: https://pnpm.io/continuous-integration#github-actions
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        env:
          PR_NUM: ${{ github.event.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "APP_VERSION=v$(jq -r .version package.json)-pr-${PR_NUM}-build-${GITHUB_RUN_NUMBER}-preview" >> .env.production.local
          echo "APP_LINK=${PR_URL}" >> .env.production.local
          cat .env.production.local
          pnpm run build && touch build-ok
      - name: Archive build artifacts
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: online-inquiry-tool-pr-${{ github.event.number }}-build-${{ github.run_number }}
          path: |
            dist
          retention-days: 30 # default 90 days
      - name: Set result
        if: ${{ always() }}
        id: result
        run: 'test -f build-ok && echo "result=- **âœ… build**: Success ðŸ› ï¸" >> $GITHUB_OUTPUT || echo "result=- **ðŸ›‘ build**: FAILED ðŸ’©" >> $GITHUB_OUTPUT'

  deploy:
    name: Deploy
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}
      test-link: ${{ steps.test-link.outputs.test-link }}
    steps:
      - name: Get build artifact
        id: build-and-deploy
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: online-inquiry-tool-pr-${{ github.event.number }}-build-${{ github.run_number }}
          path: dist
      - name: Configure AWS credentials for S3 deployment
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # aws cli is available already in GH image
      # see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
      #      https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
      - name: Deploy artifacts to S3
        env:
          PR_NUM: ${{ github.event.number }}
        run: aws s3 cp --recursive dist/ "s3://${{ secrets.AWS_BUCKET_NAME }}/pr/${PR_NUM}/${GITHUB_RUN_NUMBER}/" && touch deploy-ok
      - name: Set result
        if: ${{ always() }}
        id: result
        env:
          PR_NUM: ${{ github.event.number }}
        # NOTE: using secrets in output make GitHub to skip output!
        run: 'test -f deploy-ok && echo "result=- **âœ… deploy**: Success ðŸš€ Test it here: <${APP_SERVER}/pr/${PR_NUM}/${GITHUB_RUN_NUMBER}/index.html>" >> $GITHUB_OUTPUT || echo "result=- **ðŸ›‘ deploy**: FAILED ðŸ’”" >> $GITHUB_OUTPUT'
      - name: Set test link
        if: ${{ always() }}
        id: test-link
        env:
          PR_NUM: ${{ github.event.number }}
        # NOTE: using secrets in output make GitHub to skip output!
        run: echo "test-link=${APP_SERVER}/pr/${PR_NUM}/${GITHUB_RUN_NUMBER}/index.html" >> $GITHUB_OUTPUT

  commitlint:
    name: Run commitlint
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}
      warn-many-commits: ${{ steps.warn-many-commits.outputs.warn-many-commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@0d749a1a91d4770e983a7b8f83d4a3f0e7e0874e # v5.4.4
        with:
          configFile: .commitlintrc.yaml
      - name: Fail if too many commits
        if: ${{ github.event.pull_request.commits > 30 }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.setFailed('You have ${{ github.event.pull_request.commits }} commits in your PR! Hard limit is 30.')
      - name: Mark passed
        run: touch commits-ok
      - name: Set result
        if: ${{ always() }}
        id: result
        run: 'test -f commits-ok && echo "result=- **âœ… commitlint**: Success ðŸ‘" >> $GITHUB_OUTPUT || echo "result=- **ðŸ›‘ commitlint**: FAILED ðŸ§" >> $GITHUB_OUTPUT'
      - name: Set many commits warning
        if: ${{ always() }}
        id: warn-many-commits
        # NOTE: Multiline strings need special handling.
        # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        env:
          N: ${{ github.event.pull_request.commits }}
        run: |
          if [[ "${N}" -gt 30 ]]; then \
            printf "warn-many-commits<<EOF\n\n**ðŸ›‘ ERROR: You have ${N} commits in your PR. GitHub API and/or wagoid/commitlint-github-action seems to be limited to 30 commits / PR, so commitlint check will fail! ðŸ›‘**\n\nEOF\n" >> $GITHUB_OUTPUT; \
          elif [[ "${N}" -ge 20 ]]; then \
            printf "warn-many-commits<<EOF\n\n**âš ï¸ WARNING: You have ${N} commits in your PR. GitHub API and/or wagoid/commitlint-github-action seems to be limited to 30 commits / PR, so commitlint check starts failing after that count! âš ï¸**\n\nEOF\n" >> $GITHUB_OUTPUT; \
          else echo "warn-many-commits=" >> $GITHUB_OUTPUT; fi

  src-lints:
    name: Run eslint and translations check
    # Run after build just in case to avoid cache getting messed up, but run always.
    # (Not sure if setup-node could handle parallel access).
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      es-result: ${{ steps.es-result.outputs.result }}
      tr-result: ${{ steps.tr-result.outputs.result }}
      tr-details: ${{ steps.tr-result.outputs.details }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          cache: 'pnpm' # cache example form: https://pnpm.io/continuous-integration#github-actions
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run eslint
        run: pnpm run lint && touch eslint-ok
      - name: Run translation check
        if: ${{ always() }}
        run: |
          pnpm run build:tools
          node dist.local/tools/lang-check.js -m dist.local/tr-out.md && touch tr-ok
      - name: Set eslint result
        if: ${{ always() }}
        id: es-result
        run: 'test -f eslint-ok && echo "result=- **âœ… eslint**: Success ðŸ‘" >> $GITHUB_OUTPUT || echo "result=- **ðŸ›‘ eslint**: FAILED ðŸ§" >> $GITHUB_OUTPUT'
      - name: Set translations check result
        if: ${{ always() }}
        id: tr-result
        # NOTE: Multiline strings need special handling.
        # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
        run: |
          test -f tr-ok && echo "result=- **âœ… translations check**: Success ðŸ‘" >> $GITHUB_OUTPUT || echo "result=- **ðŸ›‘ translations check**: FAILED ðŸ§ (see \"Translation check problems below\")" >> $GITHUB_OUTPUT
          output=$(cat dist.local/tr-out.md)
          test -f tr-ok && echo "details=" >> $GITHUB_OUTPUT || printf "details<<EOF\n${output}\nEOF\n" >> $GITHUB_OUTPUT

  comment-success:
    name: Leave a comment on success
    needs: [build, deploy, commitlint, src-lints]
    runs-on: ubuntu-latest
    steps:
      - name: Leave a comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GH_TOKEN_RELEASE_BOT }}
          # Note the indentation of body!
          # See: https://github.com/actions/github-script/issues/247#issuecomment-1079839739
          # and: https://github.com/actions/github-script#welcome-a-first-time-contributor
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Great success! ðŸ¥³ Your pull request was built and has been deployed for testing: <${{ needs.deploy.outputs.test-link }}>
            ${{ needs.commitlint.outputs.warn-many-commits }}
            **Job summary:**

            ${{ needs.build.outputs.result }}
            ${{ needs.deploy.outputs.result }}
            ${{ needs.commitlint.outputs.result }}
            ${{ needs.src-lints.outputs.es-result }}
            ${{ needs.src-lints.outputs.tr-result }}

            ${{ needs.src-lints.outputs.tr-details }}

            Build job with artifacts is here: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>`
            })

  comment-failure:
    name: Leave a comment on failure
    if: ${{ failure() }}
    needs: [build, deploy, commitlint, src-lints]
    runs-on: ubuntu-latest
    steps:
      - name: Leave a comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GH_TOKEN_RELEASE_BOT }}
          # Note the indentation of body!
          # See: https://github.com/actions/github-script/issues/247#issuecomment-1079839739
          # and: https://github.com/actions/github-script#welcome-a-first-time-contributor
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Something went wrong with your PR's build job! ðŸ˜­ See summary and build job link below ðŸ‘‡
            ${{ needs.commitlint.outputs.warn-many-commits }}
            **Job summary:**

            ${{ needs.build.outputs.result }}
            ${{ needs.deploy.outputs.result }}
            ${{ needs.commitlint.outputs.result }}
            ${{ needs.src-lints.outputs.es-result }}
            ${{ needs.src-lints.outputs.tr-result }}

            ${{ needs.src-lints.outputs.tr-details }}

            Build job with artifacts is here: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>`
            })
